name: CI/CD Pipeline

on:
  # Trigger na push do main
  push:
    branches: [ main ]
  # Trigger manualny
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    env:
      NODE_VERSION: '20'
      # Dodaj tutaj inne zmienne środowiskowe specyficzne dla joba
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      # Test user credentials
      E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        continue-on-error: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC || env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm run test
        env:
          CI: true
        
      - name: Run build
        run: npm run build
        env:
          CI: true
